src/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

src/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', FirstItemRedirect.as_view(), name='home'),
    path('item/<int:pk>/', ItemDetailView.as_view(), name='item_detail'),
    path('item/add/<int:item_id>/', CartManageView.as_view(), name='cart_manage'),
    path('buy/', CreateOrderFromCartView.as_view(), name='item_buy'),
    path('buy/<int:pk>/', CreateOrderFromCartView.as_view(), name='cart_buy')

]

src/main/models.py
from django.db import models


class Currency(models.TextChoices):
    RUB = 'rub', 'рубль'
    USD = 'usd', 'доллар'


class OrderModifier(models.Model):
    name = models.CharField(max_length=100)
    stripe_id = models.CharField()
    currency = models.CharField(choices=Currency.choices, default=Currency.RUB)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Discount(OrderModifier):
    class Meta:
        verbose_name = 'Скидка'
        verbose_name_plural = 'Скидки'


class Tax(OrderModifier):
    class Meta:
        verbose_name = 'Налог'
        verbose_name_plural = 'Налоги'


class Item(models.Model):
    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.FloatField()
    currency = models.CharField(choices=Currency.choices, default=Currency.RUB)

    def __str__(self):
        return self.name


class Order(models.Model):
    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    # Значение налога в платёжке применяется к товарам, а не всей корзине. Но в упрощённом примере, я просто копирую это значение к товарам
    tax = models.ForeignKey(Tax, on_delete=models.SET_NULL, blank=True, null=True)
    discount = models.ForeignKey(Discount, on_delete=models.SET_NULL, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_items')
    item = models.ForeignKey(Item, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        unique_together = ('order', 'item')

    def __str__(self):
        return f"{self.item.name} x {self.quantity}"

src/main/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from django.views.generic.detail import DetailView
from django.shortcuts import redirect
from django.http import Http404
from django.views import View
from .services.payment import *
from .models import *


class ItemDetailView(DetailView):
    model = Item
    template_name = 'main/item_page.html'
    context_object_name = 'item'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        item = self.get_object()
        prev_item = Item.objects.filter(id__lt=item.id).order_by('-id').first()
        next_item = Item.objects.filter(id__gt=item.id).order_by('id').first()
        context['prev_item'] = prev_item
        context['next_item'] = next_item
        return context


class CartManageView(View):
    def post(self, request, item_id):
        cart = request.session.get('cart', {})
        action = request.POST.get('_action', 'add')
        if action == 'delete':  # Проверка по значению (вместо def delete), потому что используется стандартная HTML-форма без JS.
            if str(item_id) in cart:
                del cart[str(item_id)]
        else:
            cart[str(item_id)] = cart.get(str(item_id), 0) + 1
        request.session['cart'] = cart
        return redirect(request.META.get('HTTP_REFERER', request.path))


class CreateOrderFromCartView(View):
    def get(self, request, pk=None):  # Сценарии покупки через корзину или сразу, обрабатываются одним view
        if pk is not None:
            cart = {str(pk): 1}
        else:
            cart = request.session.get('cart', {})
            if not cart:
                return redirect('/')

        try:
            order_items, tax_id, discount_id = write_order_data(cart)
        except ObjectDoesNotExist as e:
            return JsonResponse({'status': 'fail', 'error': f'Item does not exist {e}'}, status=404)
        except Exception as e:
            return JsonResponse({'status': 'fail', 'error': f'Unexpected error {e}'}, status=500)

        try:
            session, public_key = create_stripe_payment(order_items, tax=tax_id, discount=discount_id)
        except ValueError as e:
            print(f'Payment creation failed {str(e)}')
            return JsonResponse({'status': 'fail', 'error': f'{e}'}, status=400)
        except Exception as e:
            return JsonResponse({'status': 'fail', 'error': f'Unexpected error: {e}'}, status=500)

        request.session.pop('cart', None)
        request.session.modified = True

        return JsonResponse({'status': 'success', 'id': session.id, 'key': public_key})


# Главной страницы на сайте нет, поэтому делаю редирект на страницу первого товара
class FirstItemRedirect(View):
    def get(self, request):
        first_item = Item.objects.order_by('id').first()
        if not first_item:
            raise Http404

        return redirect(f'/item/{first_item.id}/')

src/main/templates/main/item_page.html
{% extends 'main/main.html' %}
{% load static %}
{% block item %}
    <div class="item-obj vertical-div" style="background-color: lightgrey;">
        <div class="item-card">
            <h1>{{ item.name }}</h1>
            <p>{{ item.description }}</p>
            <p>{{ item.price }} {{ item.currency }}</p>
            <div class="vertical-div">
                <form method="post" action="{% url 'main:cart_manage' item.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn">Добавить в корзину</button>

                </form>
                <button type="submit" id="item-buy" class="btn" data-item-id="{{ item.id }}">Купить сейчас</button>
            </div>
        </div>
        <div class="horizontal-div">
            {% if prev_item %}
                <a href="{% url 'main:item_detail' prev_item.id %}" class="btn">← Назад</a>
            {% else %}
                <span class="btn disabled">← Назад</span>
            {% endif %}

            {% if next_item %}
                <a href="{% url 'main:item_detail' next_item.id %}" class="btn">Вперёд →</a>
            {% else %}
                <span class="btn disabled">Вперёд →</span>
            {% endif %}
        </div>
    </div>
{% endblock %}

src/main/templates/main/main.html
{% load static %}
{% load get_item %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">

</head>
<body>
    <header>
        <div class="vertical-div" style="background-color: cornsilk;">
            <div class="horizontal-div">
                <p style="font-size: 26px; margin-top: 0;">Корзина</p>
                <button id="cart-buy" class="btn">К оплате</button>
            </div>
            <p class="cart-count">Число товаров {{ cart.items_count }}</p>
            <div class="cart-item-list">
                {% for item in cart.items %}
                    <div class="horizontal-div">
                        <p class="cart-item">
                            Товар {{ item.name }} за {{ item.price }} {{ item.currency }} {{ cart.quantities|get_item:item.id }} шт.
                        </p>
                        <form method="post" action="{% url 'main:cart_manage' item.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="_action" value="delete">
                            <button type="submit" class="cross-btn">X</button>
                        </form>
                        </div>
                {% endfor %}
            </div>

        </div>
    </header>
    <main>
        {% block item %}{% endblock %}
    </main>
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'main/js/main.js' %}"></script>

</body>
</html>